---
title: "First Knit"
author: "Amir Johnson"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attend high school at Eastside high school. I also graduated from Eastside high school too. No, they are both equal, but when I was in middle school I liked math way more than English. The subject I did the best in was math in high school.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have an apple computer at home. From a scale of 1 to 10 I am at a 7. At home I have a good internet connection and I am able to do work.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer people to call me by my first name Amir. I don't have any nicknames, everyone always called me by my first name.
  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I am trying to achieve My CDL license. The college subject that interests me the most is psychology because I get to learn about the human mind and body. I am trying to achieve my bachelors degree.
  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
No, I have never visited an foreign country. I might go to japan In the future.I have never been in the military. I would go to the air force branch. I have a friend there right now.  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
No, I did not take math 115 or math 116. No, I did not know anything about math 115, I took math 135 and failed it so now I'm taking math 115.I need to attain an A grade so I could go on in stats.  
   
 






  




